### ISSUE TITLE
Problem with example

### ISSUE THREAD

**Issue by JoeD84** [dotnet/dotnet-api-docs.de-de#14]
The example declares the page variable inside a using statement and uses it outside of the statement which is not valid.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 15cec986-10d1-6026-d860-4bb72f0699b3
* Version Independent ID: 1ecb33f0-a686-2e54-ac38-d3fa24c7e64f
* Content: [Socket Class (System.Net.Sockets)](https://docs.microsoft.com/de-de/dotnet/api/system.net.sockets.socket?view=netframework-4.7.2)
* Content Source: [xml/System.Net.Sockets/Socket.xml](https://github.com/dotnet/dotnet-api-docs.de-de/blob/live/xml/System.Net.Sockets/Socket.xml)
* Product: **dotnet-api**
* GitHub Login: @karelz
* Microsoft Alias: **ncldev**

**Comment by CeciAc** [comment]
Issue moved to [dotnet/dotnet-api-docs #1622](https://github.com/dotnet/dotnet-api-docs/issues/1622) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @JoeD84 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/dotnet/dotnet-api-docs/issues/1622.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
