### ISSUE TITLE
Add description

### ISSUE THREAD

**Issue by Beautyod** [dotnet/dotnet-api-docs.de-de#18]
Please add a description for this method.

I wonder what happens when the key already exists.
Just nothing or will it throw an exception.
Such information is important for the users.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 81498c77-e953-d79b-d758-09e63edc61fd
* Version Independent ID: 51907d96-b483-143d-0462-45d3b3cd2b30
* Content: [Dictionary&lt;TKey,TValue&gt;.TryAdd(TKey, TValue) Method (System.Collections.Generic)](https://docs.microsoft.com/de-de/dotnet/api/system.collections.generic.dictionary-2.tryadd?view=netcore-2.2&viewFallbackFrom=netframework-4.6.2)
* Content Source: [xml/System.Collections.Generic/Dictionary`2.xml](https://github.com/dotnet/dotnet-api-docs.de-de/blob/live/xml/System.Collections.Generic/Dictionary`2.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
Issue moved to [dotnet/dotnet-api-docs #2062](https://github.com/dotnet/dotnet-api-docs/issues/2062) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/dotnet/dotnet-api-docs/issues/2062

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
