### ISSUE TITLE
Dubious information

### ISSUE THREAD

**Issue by TaWulf** [dotnet/dotnet-api-docs.de-de#21]
This,,:

'Initializes a new instance of the AnnotationPathPoint class with the specified legend name.'

,,seems a misplaced piece of information.  It is obviously just a Legend not an AnnotationPathPoint  that gets created. This mistake is also visible in Intellisense and in the ASP version.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 76410ceb-3469-32f2-a52f-0b31628dbaa8
* Version Independent ID: 7b38058a-589b-ed37-8b10-ff4e8c96b0f0
* Content: [Legend Constructor (System.Windows.Forms.DataVisualization.Charting)](https://docs.microsoft.com/de-de/dotnet/api/system.windows.forms.datavisualization.charting.legend.-ctor?view=netframework-4.7.2#feedback)
* Content Source: [xml/System.Windows.Forms.DataVisualization.Charting/Legend.xml](https://github.com/dotnet/dotnet-api-docs.de-de/blob/live/xml/System.Windows.Forms.DataVisualization.Charting/Legend.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
Issue moved to [dotnet/dotnet-api-docs #2198](https://github.com/dotnet/dotnet-api-docs/issues/2198) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @TaWulf 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/dotnet/dotnet-api-docs/issues/2198

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
