### ISSUE TITLE
ArgumentException for Min<TSource>(IEnumerable<TSource>) not documented

### ISSUE THREAD

**Issue by TChristoph** [dotnet/dotnet-api-docs.de-de#24]
If no object in the sequence implements IComparable or IComparable&lt;T&gt;, Min&lt;TSource&gt;(IEnumerable&lt;TSource&gt;) will throw an ArgumentException. This fact should be documented.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: d3fab52b-b1d1-cd4d-8dac-cf24ba6005a8
* Version Independent ID: 9662f45d-7018-f1e4-be4a-9632b9d8ac94
* Content: [Enumerable.Min Method (System.Linq)](https://docs.microsoft.com/de-de/dotnet/api/system.linq.enumerable.min?view=netstandard-2.0#feedback)
* Content Source: [xml/System.Linq/Enumerable.xml](https://github.com/dotnet/dotnet-api-docs.de-de/blob/live/xml/System.Linq/Enumerable.xml)
* Product: **dotnet-api**
* Technology: **system.linq**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
Issue moved to [dotnet/dotnet-api-docs #2275](https://github.com/dotnet/dotnet-api-docs/issues/2275) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @LinqLover 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/dotnet/dotnet-api-docs/issues/2275

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
