### ISSUE TITLE
timeout or no timeout?

### ISSUE THREAD

**Issue by mbrenn** [dotnet/dotnet-api-docs.de-de#25]
Invoke(Action, DispatcherPriority, CancellationToken, TimeSpan) defines timeout variable as 'minimum time before start' while other overloads define timeout variable 'as maximum time until end'. 
Seems to be wrong or confusing.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 8adbf2d5-66d0-15ab-743a-21ec03b05295
* Version Independent ID: 5269116e-7645-b2ba-839a-1aca693431f8
* Content: [Dispatcher.Invoke Method (System.Windows.Threading)](https://docs.microsoft.com/de-de/dotnet/api/system.windows.threading.dispatcher.invoke?view=netframework-4.8#feedback)
* Content Source: [xml/System.Windows.Threading/Dispatcher.xml](https://github.com/dotnet/dotnet-api-docs.de-de/blob/live/xml/System.Windows.Threading/Dispatcher.xml)
* Product: **dotnet-api**
* Technology: **system.windows**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
Issue moved to [dotnet/dotnet-api-docs #2409](https://github.com/dotnet/dotnet-api-docs/issues/2409) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @mbrenn

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/dotnet/dotnet-api-docs/issues/2409

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
