### ISSUE TITLE
German section titles and banner when activated "Auf Englisch lesen"

### ISSUE THREAD

**Issue by MSeifert04** [dotnet/dotnet-api-docs.de-de#27]
When I activate the "Auf Englisch lesen" then some sections are still on german and the hint about "auto-translated" text still appears.

![Unbenannt](https://user-images.githubusercontent.com/14200878/59134065-48171b00-897a-11e9-8c9f-fe34efbef54b.png)

I would prefer it if the banner would disappear (or is the english text auto-translated) and the section titles to be english too. At least with activated "auf englisch lesen".

Not sure if this is the correct repository for the issue, however I got here by clicking on "Bearbeiten" so I hope it's not too far off.

**Comment by CeciAc** [comment]
Hello, @MSeifert04
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team


@JasonCard can you please check this issue?
thanks!

**Comment by JasonCard** [comment]
Hi @MSeifert04 

Thank you for your feedback.
The "Read in English" option is designed to display the source English text of that particular particle that was translated. However, as long as your selected language is German, the disclaimer that the article has been machine translated will still appear by design. Also, section titles that are translated as part of template will also display the translated text as selected language is German.
If you would like to see the article completely in English, then please select the English language.

Kind regards,
Microsoft DOCS International Team

cc @CeciAc
