### ISSUE TITLE
If this method is obsolete, how to replace it with the other overload?

### ISSUE THREAD

**Issue by jongleur1983** [dotnet/dotnet-api-docs.de-de#32]
It's mentioned, that the `ToString(DateTime, XmlDateTimeSerializationMode)` overload of ToString should be used instead.
But which enum value of XmlDateTimeSerializationMode matches the old behavior? (if any)?

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 15a194ea-bdb0-e1f2-1b8b-11c2a255732d
* Version Independent ID: 181423b7-1c3a-2a27-023b-4db7550543c7
* Content: [XmlConvert.ToString Method (System.Xml)](https://docs.microsoft.com/de-de/dotnet/api/system.xml.xmlconvert.tostring?view=netframework-4.8#feedback)
* Content Source: [xml/System.Xml/XmlConvert.xml](https://github.com/dotnet/dotnet-api-docs.de-de/blob/live/xml/System.Xml/XmlConvert.xml)
* Product: **dotnet-api**
* Technology: **system.xml**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
Issue moved to [dotnet/dotnet-api-docs #2665](https://github.com/dotnet/dotnet-api-docs/issues/2665) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @jongleur1983

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/dotnet/dotnet-api-docs/issues/2665

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
