### ISSUE TITLE
Formatting of code example

### ISSUE THREAD

**Issue by Prodigio** [dotnet/dotnet-api-docs.de-de#33]
The formatting of the code example could be improved here.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 17f48aba-d3d1-df27-9ab0-956694ed8102
* Version Independent ID: c740827c-69fb-54b7-54a0-e4312b856454
* Content: [HttpWebRequest.BeginGetResponse(AsyncCallback, Object) Method (System.Net)](https://docs.microsoft.com/de-de/dotnet/api/system.net.httpwebrequest.begingetresponse?view=netframework-4.8)
* Content Source: [xml/System.Net/HttpWebRequest.xml](https://github.com/dotnet/dotnet-api-docs.de-de/blob/live/xml/System.Net/HttpWebRequest.xml)
* Product: **dotnet-api**
* Technology: **system.net**
* GitHub Login: @karelz
* Microsoft Alias: **ncldev**

**Comment by CeciAc** [comment]
Hello, @Prodigio 
 
We truly appreciate your comment and we strive to improve your experience in docs.microsoft.com. However, we need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment?
 
Kind regards,
Microsoft DOCS International Team
