### ISSUE TITLE
Examples are missing in this documentation

### ISSUE THREAD

**Issue by Andrum87** [dotnet/dotnet-api-docs.de-de#6]
Please provide some examples of using the DataGridComboBoxColumn.TextBinding Property in C# Code as well as in XAML Code. 

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 1ab4c308-71f2-38ae-e58e-67b00c6cbb69
* Version Independent ID: 29ee69c1-21b3-6a75-a32a-76880938a194
* Content: [DataGridComboBoxColumn.TextBinding Property (System.Windows.Controls)](https://docs.microsoft.com/de-de/dotnet/api/system.windows.controls.datagridcomboboxcolumn.textbinding?view=netframework-4.7.2#System_Windows_Controls_DataGridComboBoxColumn_TextBinding)
* Content Source: [xml/System.Windows.Controls/DataGridComboBoxColumn.xml](https://github.com/dotnet/dotnet-api-docs.de-de/blob/live/xml/System.Windows.Controls/DataGridComboBoxColumn.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by LisandroSu** [comment]
Issue moved to [dotnet/dotnet-api-docs #1272](https://github.com/dotnet/dotnet-api-docs/issues/1272) via [**ZenHub**](https://www.zenhub.com/)

**Comment by LisandroSu** [comment]
Hello, @Andrum87 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/dotnet/dotnet-api-docs/issues/1272.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
